//This file is auto_generated do not edit.
#define libi_enabled
#define libmath2d_enabled
#define libbasicmath_enabled
#define libfxdomain_enabled
#define librpn_enabled
#define libshape_enabled
#define libemission_enabled
#define libmemory_enabled
#define libdos_enabled
#define liblight_enabled
#define libjson_enabled
#define libheat_enabled
#define libexciton_enabled
#define libsinglet_enabled
#define libray_enabled
#define libcolor_enabled
#define libmeasure_enabled
#define libcontacts_enabled
#define lib_enabled
#define libdump_enabled
#define libdevice_enabled
#define libserver_enabled
#define libmesh_enabled
#define libperovskite_enabled
#define libnewtontricks_enabled
#define libsimplex_enabled
#define libfdtd_enabled
#define libmode_enabled
#define liblock_enabled
#define libcircuit_enabled
#define libfit_enabled
#define dbus
#define enable_server
